spring.application.name=reap-admin-api
server.port=${PORT}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

spring.datasource.url=jdbc:postgresql://awseb-e-yqqn3pmdef-stack-awsebrdsdatabase-xuipgoysbwv6.cfuya0giaury.ap-south-1.rds.amazonaws.com:5432/reap_db
spring.datasource.username=
spring.datasource.password=

# Connection Pool Configuration
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.leak-detection-threshold=60000

# Query Performance
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true


 Hibernate JPA configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext


client.id=
client.secret=
base.url=https://dev-nabard.zencite.in

spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false


#JWT
app.jwtSecret=
app.jwtExpirationInMs = 60000000

spring.main.allow-circular-references=true

# Enable multipart handling
spring.servlet.multipart.enabled=true
# Max file size
spring.servlet.multipart.max-file-size=20MB
# Max request size
spring.servlet.multipart.max-request-size=20MB

logging.level.org.springframework.transaction=INFO
logging.level.org.hibernate.SQL=TRACE
logging.level.org.hibernate.type=TRACE

logging.level.org.springframework.security=DEBUG
logging.level.com.tl.reap.security=DEBUG

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.com.tl.reap_admin_api.service=DEBUG
logging.file.path=../logs/

# Set the logging pattern for file
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

#logging.level.org.springdoc=DEBUG
#logging.level.io.swagger=DEBUG

#logging.level.com.fasterxml.jackson.databind=DEBUG
#logging.level.com.fasterxml.jackson.core=DEBUG

#Kpoint configuration
kpoint.client.id=
kpoint.client.secret=
kpoint.client.displayname=Sinujamal@123
kpoint.client.email=sinu.jamal@tensorlogic.ai

aws.access-key=
aws.secret-key=
aws.s3.region=us-east-2
aws.s3.crsimg.bucket-name=courseimgsv1
aws.s3.crsimg.bucket-url=https://courseimgsv1.s3.us-east-2.amazonaws.com/courses

aws.s3.crsimg.testimonial-bucket-name=testimonialimgs
